### ISSUE TITLE
Crash when opening Pet Menu

### ISSUE THREAD

**Issue by Leon-JavaScript** [bowser0000/SkyblockMod#170]
Since the new update from today, the game is crashing when opening the pet menu when you've set up favorite pets.
```
Description: Rendering screen

java.lang.NumberFormatException: For input string: "§7[Lvl 200"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at me.Danker.features.PetColours.onGuiRender(PetColours.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_190_PetColours_onGuiRender_GuiChestBackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at me.Danker.DankersSkyblockMod.onGuiRender(DankersSkyblockMod.java:486)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_60_DankersSkyblockMod_onGuiRender_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:595)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:72)
	at net.minecraft.client.gui.inventory.GuiChest.drawScreen(SourceFile)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1436)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.handler$zpl000$run(Minecraft.java:3250)
	at net.minecraft.client.Minecraft.run(Minecraft.java)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by bowser0000** [comment]
Fixed in v2.3
